package br.com.mv.demo.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import br.com.mv.demo.model.converters.EnumTipoTesteConverter;
import br.com.mv.demo.model.type.EnumTipoTeste;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "MAPPED_TESTE")
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
public class MappedTeste implements Serializable {
	
	/**
	 * Generated by IDE
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	@SequenceGenerator(name = "SEQ_MAPPED_TESTE", sequenceName = "SEQ_MAPPED_TESTE", allocationSize = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_MAPPED_TESTE")
	private Long id;
	
	@Column(name = "TP_SITUACAO")
	@Convert(converter = EnumTipoTesteConverter.class)
	private EnumTipoTeste situacaoTeste;
	
	@Column(name = "DESCRICAO")
	private String descricao;

}
