package br.com.mv.demo.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Embeddable;

import org.hibernate.annotations.Formula;

import br.com.mv.demo.model.converters.EnumTipoTratamentoNomeConverter;
import br.com.mv.demo.model.type.EnumTipoTratamentoNome;
import lombok.Getter;
import lombok.Setter;

@Embeddable
@Getter @Setter
public class Nome implements Serializable {
	
	/**
	 * Generated by IDE
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "TRATAMENTO")
	@Convert(converter = EnumTipoTratamentoNomeConverter.class)
	private EnumTipoTratamentoNome tratamento;
	
	@Column(name = "PRIMEIRO_NOME")
	private String primeiroNome;
	
	@Column(name = "NOME_MEIO")
	private String nomeDoMeio;
	
	@Column(name = "ULTIMO_NOME")
	private String ultimoNome;
	
	@Column(name = "APELIDO")
	private String apelido;
	
	@Formula("TRATAMENTO || ' ' || PRIMEIRO_NOME || ' ' || NOME_MEIO || ' ' || ULTIMO_NOME")
	private String nomeCompleto;

}
