application:
    cadastros-basicos-flex-app-uri: http://192.168.254.75:8081/cadastros-basicos-flex
banner:
    location: classpath:/config/banner/banner.txt
multipart:
    enabled: true
    max-file-size: 3Mb
    max-request-size: 30Mb
security:
    basic:
        enabled: false
server:
    compression:
        enabled: true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - text/css
            - text/javascript
            - application/javascript
spring:
    application:
        name: demo
    data:
        jpa:
            repositories: 
                enabled: true
    jackson:
        locale: pt_BR
        time-zone: America/Sao_Paulo
    jpa:
        database: oracle
        database-platform: org.hibernate.dialect.Oracle12cDialect
        properties:
            hibernate.default_schema: DBAMVFOR
        show-sql: true
        open-in-view: true
    messages:
        basename: messages/messages
        encoding: UTF-8
        cache-seconds: -1
    mvc:
        locale: pt_BR 
    profiles:
        active: dev
    resources:
        chain:
          enabled: true
          strategy:
            content:
              enabled: true
              paths: /**