liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: dbamvfor
    user: dbamvfor
    password: dbamvfor
logging:
    file: ../logs/${spring.application.name}.log
spring:  
    profiles: prod
    datasource:
        jndi-name: java:comp/env/jdbc/demo
        initialize: false
    mail:
        host: localhost
        port: 25
    resources:
        cache-period: 31556926
    thymeleaf:
        cache: true